### ISSUE TITLE
problem creating df_mu object with SIBER

### ISSUE THREAD

**Issue by gccardozo-ferreira** [benjaminhlina/nichetools#17] opened 2024-09-30 12:21 UTC
Hi Benjamin,

As I told you before, I'm encountering an error while creating the 'df_mu' object using nichetools and SIBER. Here is the error message:
Error in extract_mu(ellipses_posterior, pkg = "SIBER", data_format = "wide", :
unused argument (community_df = cg_names)

I used reprex() as you suggested. I've never done it, but according to [reprex](https://reprex.tidyverse.org/), I should call 'reprex()' while having selected the part of my code which is causing the problem. So, hoping I did right, here's what I got:

``` r
df_mu <- extract_mu(ellipses_posterior, pkg = "SIBER", data_format = "wide", 
                    isotope_a = "d13c", isotope_b = "d15n", community_df = cg_names)
#> Error in extract_mu(ellipses_posterior, pkg = "SIBER", data_format = "wide", : could not find function "extract_mu"
```

<sup>Created on 2024-09-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
  

**Here is my whole code till I get the problem:**
```r
data_trindade <- read.table("trindade_fgroup.txt",header=T)

data_trindade <- data_trindade[,c("iso1","iso2","group","community")]
head(data_trindade)

data_trindade$group <- gsub(" ", "_", data_trindade$group)
data_trindade$community <- gsub(" ", "_", data_trindade$community)

aggregate(data_trindade[1:2],data_trindade[3], mean)
aggregate(data_trindade[1:2],data_trindade[4], mean)


glimpse(data_trindade)

data_trindade <- data_trindade %>%
  mutate(
    group = factor(group), 
    community = factor(community), 
    group_id = as.numeric(group) %>% 
      as.character(),
    community_id = as.numeric(community) %>%
      as.character()
  ) %>% 
  rename(
    group_name = group,
    community_name = community,
    group = group_id,
    community = community_id
  )

glimpse(data_trindade)


# ---- create name with group and community data frame ----
cg_names <- data_trindade %>%
  distinct(group,
           community, 
           group_name, 
           community_name) %>%
  
  arrange(community, group)

#---- create community names data frame ---- 
c_names <- data_trindade %>% 
  distinct(community, 
           community_name) %>%
  arrange(community)

#---- plot biplot to confirm the correct structure.
ggplot(data = data_trindade, aes(x = iso1, y = iso2,
                                     colour = group_name)) +
  geom_point(size = 3) +
  facet_wrap(~ community_name) + 
  scale_colour_viridis_d(option = "D", begin = 0, end = 1,
                         name = "Groups", alpha = 0.75) + 
  theme_bw(
    base_size = 15
  ) + 
  theme(
    strip.background = element_blank(),
    panel.grid = element_blank(), 
    axis.title = element_markdown(),
    legend.position = "inside",
    legend.position.inside = c(0.65, 0.75)
  ) + 
  labs(
    x = paste0("\U03B4","<sup>", 13, "</sup>", "C", " (‰)"),
    y = paste0("\U03B4","<sup>", 15, "</sup>", "N", " (‰)")
  )



data_trindade <- data_trindade %>% 
  dplyr::select(iso1, iso2, group, community) %>%
  arrange(community, group) %>% 
  as.data.frame() 


# ---- Convert to {SIBER} object ---- 
siber.trindade <- createSiberObject(data_trindade)


#Bayesian Ellipse Analysis
#options for running jags
parms <- list()
parms$n.iter <- 2 * 10^4   # number of iterations to run the model for
parms$n.burnin <- 1 * 10^3 # discard the first set of values
parms$n.thin <- 10     # thin the posterior by this many
parms$n.chains <- 2        # run this many chains

#fit the ellipses which uses an Inverse Wishart prior on the covariance matrix Sigma, and a vague normal prior on the means.
priors <- list()
priors$R <- 1 * diag(2)
priors$k <- 2
priors$tau.mu <- 1.0E-3

#run the model using the function siberMVN().
ellipses_posterior <- siberMVN(siber.trindade, parms, priors)


#Extract posterior distributions for μ and Σ
df_mu <- extract_mu(ellipses_posterior, pkg = "SIBER", 
                    data_format = "wide", 
                    isotope_a = "d13c", isotope_b = "d15n"),
                    community_df = cg_names)

Error in extract_mu(ellipses_posterior, pkg = "SIBER", data_format = "wide", :
unused argument (community_df = cg_names)
```

**Comment by gccardozo-ferreira** [comment] 2024-09-30 12:48
Just an addition, I tried the vignette available [here](examples/nicheROVER-package.R) on GitHub without changing anything, i.e. using `demo.siber.data.2` and got the very same issue.

**Comment by benjaminhlina** [comment] 2024-09-30 16:55
Hi @gccardozo-ferreira, 

Thank you for moving this issue, as the issue does not have anything to do with `{SIBER}` but is an issue with `{nichetools}`. A reproducible example is a set of code that will work on anyone's computer, the example code you shared will not work on my computer due to me not having the `data_trindade` data frame. Thank you for noticing the error occurs also when using `demo.siber.data.2`, however, the link you provided does not work. 

The CRAN version of `{nichetools}` has `extract_mu()` with the following arguments:
```r
extract_mu(
  data,
  pkg = NULL,
  isotope_a = NULL,
  isotope_b = NULL,
  data_format = NULL
)
```
 You will notice that that it does not have the argument `community_df`, hence why it is erroring. The vignette for the [CRAN version](https://cran.r-project.org/web/packages/nichetools/vignettes/using-nichetools-with-the-package-SIBER.html) also demonstrates how to use the function and it does not have the `community_df` argument. Where the confusion is occurring, is I have added that argument in the newest version (0.3.2-(fall-fieldwork)) but that version is not currently on CRAN and the website is building the newest version not the CRAN version. I apologize for all of the confusion. 

To demonstrate the error I have made a reprex using `demo.siber.data.2` and the version 0.3.1 downloaded from CRAN. This inconsistency has been fixed in the [R-universe](https://benjaminhlina.r-universe.dev/nichetools) version (0.3.2) of the package and the developer version of the package on [GitHub](https://github.com/benjaminhlina/nichetools) but not the CRAN version. I will be pushing this version (0.3.2) to CRAN shortly. Thank you for reporting the error and inconsistencies, I apologize for them being there. In the future, the version that builds [the website](https://benjaminhlina.github.io/nichetools/) and the CRAN version will be the same. 

To use `extract_mu()` that has the argument `community_df`, please re-install the package using the following: 

```r
install.packages("nichetools", 
                 repos = c("https://benjaminhlina.r-universe.dev", 
                           "https://cran.r-project.org"))
```

This version (`v0.3.2-(fall-fieldwork)`) should not cause the issue you are having nor the error you see in the below reprex: 

``` r
library(nichetools)
#> Warning: package 'nichetools' was built under R version 4.4.1
#> version 0.3.1 ('visiting-friends').
#> Have you loaded {nicheROVER} or {SIBER}? If not, please do so.
library(SIBER)
```

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.0 (2024-04-24)
#>  os       macOS 15.0
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Toronto
#>  date     2024-09-30
#>  pandoc   3.1.11 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.3   2024-06-21 [1] CRAN (R 4.4.0)
#>  colorspace    2.1-1   2024-07-26 [1] CRAN (R 4.4.0)
#>  digest        0.6.37  2024-08-19 [1] CRAN (R 4.4.1)
#>  dplyr         1.1.4   2023-11-17 [1] CRAN (R 4.4.0)
#>  ellipse       0.5.0   2023-07-20 [1] CRAN (R 4.4.0)
#>  evaluate      0.24.0  2024-06-10 [1] CRAN (R 4.4.0)
#>  fansi         1.0.6   2023-12-08 [1] CRAN (R 4.4.0)
#>  fastmap       1.2.0   2024-05-15 [1] CRAN (R 4.4.0)
#>  fs            1.6.4   2024-04-25 [1] CRAN (R 4.4.0)
#>  generics      0.1.3   2022-07-05 [1] CRAN (R 4.4.0)
#>  ggplot2       3.5.1   2024-04-23 [1] CRAN (R 4.4.0)
#>  glue          1.7.0   2024-01-09 [1] CRAN (R 4.4.0)
#>  gtable        0.3.5   2024-04-22 [1] CRAN (R 4.4.0)
#>  htmltools     0.5.8.1 2024-04-04 [1] CRAN (R 4.4.0)
#>  knitr         1.48    2024-07-07 [1] CRAN (R 4.4.0)
#>  lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.4.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.4.0)
#>  munsell       0.5.1   2024-04-01 [1] CRAN (R 4.4.0)
#>  nicheROVER    1.1.2   2023-10-13 [1] CRAN (R 4.4.0)
#>  nichetools  * 0.3.1   2024-09-06 [1] CRAN (R 4.4.1)
#>  pillar        1.9.0   2023-03-22 [1] CRAN (R 4.4.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.4.0)
#>  purrr         1.0.2   2023-08-10 [1] CRAN (R 4.4.0)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.4.0)
#>  reprex        2.1.1   2024-07-06 [1] CRAN (R 4.4.0)
#>  rlang         1.1.4   2024-06-04 [1] CRAN (R 4.4.0)
#>  rmarkdown     2.28    2024-08-17 [1] CRAN (R 4.4.0)
#>  rstudioapi    0.16.0  2024-03-24 [1] CRAN (R 4.4.0)
#>  scales        1.3.0   2023-11-28 [1] CRAN (R 4.4.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.4.0)
#>  SIBER       * 2.1.9   2023-10-19 [1] CRAN (R 4.4.0)
#>  tibble        3.2.1   2023-03-20 [1] CRAN (R 4.4.0)
#>  tidyr         1.3.1   2024-01-24 [1] CRAN (R 4.4.0)
#>  tidyselect    1.2.1   2024-03-11 [1] CRAN (R 4.4.0)
#>  utf8          1.2.4   2023-10-22 [1] CRAN (R 4.4.0)
#>  vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.4.0)
#>  withr         3.0.1   2024-07-31 [1] CRAN (R 4.4.0)
#>  xfun          0.47    2024-08-17 [1] CRAN (R 4.4.0)
#>  yaml          2.3.10  2024-07-26 [1] CRAN (R 4.4.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

``` r
str(demo.siber.data.2)
#> 'data.frame':    150 obs. of  4 variables:
#>  $ iso1     : num  -11.05 -8.81 -9.26 -8.38 -10.4 ...
#>  $ iso2     : num  1.02 1.98 3.29 -1.96 -3.12 ...
#>  $ group    : chr  "city" "city" "city" "city" ...
#>  $ community: chr  "dublin" "dublin" "dublin" "dublin" ...
```

``` r
demo.siber.data.2$group_name <- as.factor(demo.siber.data.2$group)

demo.siber.data.2$group <- as.numeric(demo.siber.data.2$group_name) |>
  as.character()

demo.siber.data.2$community_name <- as.factor(demo.siber.data.2$community)

demo.siber.data.2$community <- as.numeric(demo.siber.data.2$community_name) |>
  as.character()
```

``` r

cg_name <- demo.siber.data.2 |>
  dplyr::distinct(community, group, community_name, group_name)
```

``` r

demo_data <- demo.siber.data.2[, -c(5, 6)]

str(demo_data) 
#> 'data.frame':    150 obs. of  4 variables:
#>  $ iso1     : num  -11.05 -8.81 -9.26 -8.38 -10.4 ...
#>  $ iso2     : num  1.02 1.98 3.29 -1.96 -3.12 ...
#>  $ group    : chr  "1" "1" "1" "1" ...
#>  $ community: chr  "1" "1" "1" "1" ...
```

``` r

siber_demo <- createSiberObject(demo_data)
```

``` r
# options for running jags
parms <- list()
parms$n.iter <- 2 * 10^4   # number of iterations to run the model for
parms$n.burnin <- 1 * 10^3 # discard the first set of values
parms$n.thin <- 10     # thin the posterior by this many
parms$n.chains <- 2        # run this many chains

#fit the ellipses which uses an Inverse Wishart prior on the 
# covariance matrix Sigma, and a vague normal prior on the means.
priors <- list()
priors$R <- 1 * diag(2)
priors$k <- 2
priors$tau.mu <- 1.0E-3

#run the model using the function siberMVN().
ellipses_posterior <- siberMVN(siber_demo, parms, priors)
#> Compiling model graph
#>    Resolving undeclared variables
#>    Allocating nodes
#> Graph information:
#>    Observed stochastic nodes: 30
#>    Unobserved stochastic nodes: 3
#>    Total graph size: 45
#> 
#> Initializing model
#> 
#> Compiling model graph
#>    Resolving undeclared variables
#>    Allocating nodes
#> Graph information:
#>    Observed stochastic nodes: 30
#>    Unobserved stochastic nodes: 3
#>    Total graph size: 45
#> 
#> Initializing model
#> 
#> Compiling model graph
#>    Resolving undeclared variables
#>    Allocating nodes
#> Graph information:
#>    Observed stochastic nodes: 30
#>    Unobserved stochastic nodes: 3
#>    Total graph size: 45
#> 
#> Initializing model
#> 
#> Compiling model graph
#>    Resolving undeclared variables
#>    Allocating nodes
#> Graph information:
#>    Observed stochastic nodes: 30
#>    Unobserved stochastic nodes: 3
#>    Total graph size: 45
#> 
#> Initializing model
#> 
#> Compiling model graph
#>    Resolving undeclared variables
#>    Allocating nodes
#> Graph information:
#>    Observed stochastic nodes: 30
#>    Unobserved stochastic nodes: 3
#>    Total graph size: 45
#> 
#> Initializing model





extract_mu(
  data = ellipses_posterior,
  pkg = "SIBER",
  community_df = cg_name
)
#> Error in extract_mu(data = ellipses_posterior, pkg = "SIBER", community_df = cg_name): unused argument (community_df = cg_name)
```

<sup>Created on 2024-09-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by benjaminhlina** [comment] 2024-09-30 17:15
Just submitted version 0.3.2 to CRAN. Should build within the next day or two.

**Comment by benjaminhlina** [comment] 2024-09-30 17:16
Just submitted version 0.3.2 to CRAN. Should build within the next day or two.

**Closed as completed by benjaminhlina** 2024-09-30 17:16 UTC
